//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monahrq.Websites.ViewModels.Publish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monahrq.Websites.ViewModels.Publish.ValidationResults", typeof(ValidationResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text for the About Us is provided. The generated website will show it as blank..
        /// </summary>
        internal static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate cost saving for Avoidable Stays report, verify you are connected to the AHRQ QI database in the Settings\Other Connection screen..
        /// </summary>
        internal static string AhrqQiDbConnection {
            get {
                return ResourceManager.GetString("AhrqQiDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate Utilization County Rates report, Patient State/County Code must be mapped during Inpatient Discharge data import..
        /// </summary>
        internal static string CheckDatasetMappingForCounty {
            get {
                return ResourceManager.GetString("CheckDatasetMappingForCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your selected report, &quot;{0}&quot;, it is recommended that you map all your local hospitals with a correct CMS provider IDs..
        /// </summary>
        internal static string CMSProviderIdUnmapped {
            get {
                return ResourceManager.GetString("CMSProviderIdUnmapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All measures for each subtopic in the Cost and Quality Report must be selected to include the measures for reporting. &quot;{0}&quot; subtopic will not be included in the report..
        /// </summary>
        internal static string CostQualityAllFamilySelected {
            get {
                return ResourceManager.GetString("CostQualityAllFamilySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpatient Hospital Discharge (IP) file is not imported. The “Cost and Quality Report – Side By Side Comparison” report will not be generated..
        /// </summary>
        internal static string CostQualityIPFileNotImported {
            get {
                return ResourceManager.GetString("CostQualityIPFileNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate the Cost and Quality Report, verify you are connected to the AHRQ QI database in the Settings &gt; Other Connections screen..
        /// </summary>
        internal static string CostQualityQiDbConnection {
            get {
                return ResourceManager.GetString("CostQualityQiDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHRQ QI Provider file is not imported. The “Cost and Quality Report – Side By Side Comparison” report will not be generated..
        /// </summary>
        internal static string CostQualityQIProviderFileNotImported {
            get {
                return ResourceManager.GetString("CostQualityQIProviderFileNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate Utilization and cost savings reports, Cost-to-Charge-Ratios must be defined for all hospitals or else the cost data will not be included in &quot;{0}&quot;..
        /// </summary>
        internal static string CostToChargeUndefined {
            get {
                return ResourceManager.GetString("CostToChargeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heat map for Region Population Reports will not be generated in MONAHRQ as you have chosen the regional context as “Custom.”.
        /// </summary>
        internal static string CustomHeatMap {
            get {
                return ResourceManager.GetString("CustomHeatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monahrq has detected that there are Custom Region Ids in the Inpatient Discharge dataset(s) that has not been added to your custom regions data. If you want to continue, please be prepared for unexpected results as Monahrq will not be able to resolve the custom region names in your reports..
        /// </summary>
        internal static string CustomRegionAndIPCustomRegionNotMatched {
            get {
                return ResourceManager.GetString("CustomRegionAndIPCustomRegionNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No population data files have been imported.  The Rate of Discharge column will not be generated..
        /// </summary>
        internal static string CustomRegionMissingPopulationCount {
            get {
                return ResourceManager.GetString("CustomRegionMissingPopulationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom regions are defined for your website. The region based grouping and filters will not be available to your website..
        /// </summary>
        internal static string CustomRegionNotDefined {
            get {
                return ResourceManager.GetString("CustomRegionNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data set was added. The website cannot be generated. Please add datasets under “Choose Data Sets” tab..
        /// </summary>
        internal static string DatasetsMissing {
            get {
                return ResourceManager.GetString("DatasetsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection year for 1 or more of your {0} data file(s) does not match the website’s year. You may prefer to continue with publishing the website, but check your {1} utilization reports for accuracy..
        /// </summary>
        internal static string DataYearMismatchForDataSetFile {
            get {
                return ResourceManager.GetString("DataYearMismatchForDataSetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the collection years for your {0} data files match the website’s year. You may prefer to continue with publishing the website, but check your {1} utilization trending reports for accuracy..
        /// </summary>
        internal static string DataYearMismatchForTrendingDataSetFile {
            get {
                return ResourceManager.GetString("DataYearMismatchForTrendingDataSetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data element “ED Services” flag in your Inpatient Hospital discharge data file is not found or set to null. Please add or populate ED Services data element. Emergency Department report will be generated with inaccurate or not enough data..
        /// </summary>
        internal static string EmergencyDepartmentTreatAndReleaseReportEDServices {
            get {
                return ResourceManager.GetString("EmergencyDepartmentTreatAndReleaseReportEDServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inpatient Hospital discharge data  file is selected, which is needed to generate Emergency Department treat-and-release Reports. This will not create the Emergency Department reports..
        /// </summary>
        internal static string EmergencyDepartmentTreatAndReleaseReportIPDataSet {
            get {
                return ResourceManager.GetString("EmergencyDepartmentTreatAndReleaseReportIPDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regions are defined for your website. The region based grouping and filters will not be available to your website..
        /// </summary>
        internal static string HospitalsMissingRegions {
            get {
                return ResourceManager.GetString("HospitalsMissingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have provided invalid County FIPS code in your Inpatient Hospital Discharge (IP) file. Invalid codes will be aggregated as “Unknown.”.
        /// </summary>
        internal static string InvalidCountyFips {
            get {
                return ResourceManager.GetString("InvalidCountyFips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the Physician HEDIS Measures data file which has multiple rows for a single physician. One row per physician is allowed for this dataset..
        /// </summary>
        internal static string InValidPhysicianHedisDataset {
            get {
                return ResourceManager.GetString("InValidPhysicianHedisDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have provided invalid HRR/HSA region ID in your Inpatient Hospital Discharge (IP) file. Invalid codes will be aggregated as “Unknown.”.
        /// </summary>
        internal static string InvalidRegionId {
            get {
                return ResourceManager.GetString("InvalidRegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No measures are selected and the website cannot be generated..
        /// </summary>
        internal static string MeasuresMissing {
            get {
                return ResourceManager.GetString("MeasuresMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population region file has been imported, but the custom region is missing.  All the reports aggregated by the custom regions will not be generated..
        /// </summary>
        internal static string MissingCustomRegion {
            get {
                return ResourceManager.GetString("MissingCustomRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom regions and population data files have been imported.  Population Region Rates report will not be generated. In the Build Reports tab, unselect the population region reports..
        /// </summary>
        internal static string MissingCustomRegionPopulationMapping {
            get {
                return ResourceManager.GetString("MissingCustomRegionPopulationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Discharge Quarter field for some or all records in the ED dataset is missing a value. These records will not be included in the quarterly trending report..
        /// </summary>
        internal static string MissingDischargeQuarter {
            get {
                return ResourceManager.GetString("MissingDischargeQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected Hospital Profile Report that require you to import Inpatient Data. Please import Inpatient Data or uncheck Hospital Profile Report from Build Reports Tab..
        /// </summary>
        internal static string MissingHospitalProfileReportIPDataset {
            get {
                return ResourceManager.GetString("MissingHospitalProfileReportIPDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected &quot;{0}&quot; report that requires you to ensure all mapped Hospitals have a valid Local Hospital ID and CMS provider ID..
        /// </summary>
        internal static string MissingLocalHospIdOrProviderId {
            get {
                return ResourceManager.GetString("MissingLocalHospIdOrProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected Hospital Profile Report, which requires you to import Medicare Provider Utilization and Payment Data as an option. This is to include the Utilization tab. Please import Medicare Provider Utilization and Payment data or uncheck “Hospital Profile Report” from the Build Reports tab..
        /// </summary>
        internal static string MissingMedicareDataset {
            get {
                return ResourceManager.GetString("MissingMedicareDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Physician data have been imported. Physician HEDIS Measures data  will not be generated..
        /// </summary>
        internal static string MissingPhysicianReport {
            get {
                return ResourceManager.GetString("MissingPhysicianReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name was given for the website..
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected measures that support cost. The &quot;Cost and Quality Report - Side By Side Comparison&quot; will not be generated. .
        /// </summary>
        internal static string NoMeasuresForCostAndQuality {
            get {
                return ResourceManager.GetString("NoMeasuresForCostAndQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No measures for the Dataset,&quot;{0}&quot; is selected.The corresponding report(s), will not be generated..
        /// </summary>
        internal static string NoMeasuresForTheDataset {
            get {
                return ResourceManager.GetString("NoMeasuresForTheDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following measures IQI 21, IQI 22, IQI 23, IQI 24, IQI 25, IQI 33, IQI 34, PSI 17, PSI 18, PSI 19 are no longer compared in MONAHRQ as there is no risk adjusted rates available for these measures and are not recommended for comparison. If you do not want to generate these measures, uncheck these measures from the Modify Measures tab..
        /// </summary>
        internal static string ObsoleteQualityIndicators {
            get {
                return ResourceManager.GetString("ObsoleteQualityIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder you have selected doesn’t exist. The website cannot be generated..
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected Population Region Rates report that require you to define regions in your inpatient discharge file.  You will need to define your regions in the inpatient discharge data file and map these regions in the Hospital Data section. Population Region Rates report will not be generated..
        /// </summary>
        internal static string PopulationMissingRegions {
            get {
                return ResourceManager.GetString("PopulationMissingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected &quot;{0}&quot; report that requires you to map all hospitals in your QI files with the correct CMS provider ID. If you leave it unmapped, the QI measures will not appear in the generated reports..
        /// </summary>
        internal static string QIUnMappedHospitalLocalId {
            get {
                return ResourceManager.GetString("QIUnMappedHospitalLocalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to generate {0} report(s), choose &quot;the descriptive data about physician in MONAHRQ&quot; and not the &quot;website get the most current version for physician data&quot; option during the physician data import. These reports will not be generated..
        /// </summary>
        internal static string RealtimePhysicianDataCannotHaveSubReports {
            get {
                return ResourceManager.GetString("RealtimePhysicianDataCannotHaveSubReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports are selected and the website cannot be generated..
        /// </summary>
        internal static string ReportsMissing {
            get {
                return ResourceManager.GetString("ReportsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to generate a website for the year {0}; however some of the latest base data such as census population is from the year {1}. This may have impact on the analytics for your report,&quot;{2}&quot;..
        /// </summary>
        internal static string StaleBaseData {
            get {
                return ResourceManager.GetString("StaleBaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No State for the website is selected. The website cannot be generated..
        /// </summary>
        internal static string StateNotSelected {
            get {
                return ResourceManager.GetString("StateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kdjfijeijf.
        /// </summary>
        internal static string String1sdfsdf {
            get {
                return ResourceManager.GetString("String1sdfsdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different quarter is selected for each year. All years must have the same quarters selected for trending..
        /// </summary>
        internal static string TrendingQuarters {
            get {
                return ResourceManager.GetString("TrendingQuarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regions are mapped to the hospitals. The hospital level utilization reports and its data related to the region-based grouping will not be generated for your website..
        /// </summary>
        internal static string UnMappdedHospitals {
            get {
                return ResourceManager.GetString("UnMappdedHospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected &quot;{0}&quot; report that requires you to map all hospitals in your inpatient hospital discharge data file with correct CMS Provider IDs. If you leave it unmapped, these hospitals will not appear in the Utilization report..
        /// </summary>
        internal static string UnMappedHospitalLocalId {
            get {
                return ResourceManager.GetString("UnMappedHospitalLocalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected &quot;{0}&quot; report that requires you to map all local hospital IDs with the appropriate CMS Provider IDs. If you leave it unmapped, Medicare Provider Charge data will not appear in the Hospital Profile Report Utilization tab..
        /// </summary>
        internal static string UnMappedHospitalProfileLocalId {
            get {
                return ResourceManager.GetString("UnMappedHospitalProfileLocalId", resourceCulture);
            }
        }
    }
}
