BEGIN TRY

--MERGE INTO TopicTemp target 
--USING(Values ('Inpatient Hospital Utilization','Inpatient Hospital Care Utilizaton Statistics','"Weighted national estimates from HCUP Nationwide Inpatient Sample (NIS), 2009, Agency for Healthcare Research and Quality (AHRQ), based on data collected by individual States and provided to AHRQ by the States. Total number of weighted discharges in the U.S. based on HCUP NIS = 39,434,956. Statistics based on estimates with a relative standard error (standard error / weighted estimate) greater than 0.30 or with standard error = 0 are not reliable, and are designated with a †."',Null,'False',Null,1,'Utilization'),
--('ED Utilization','Emergency Department Treat and Release Utilizaton Statistics','"Weighted national estimates from HCUP Nationwide Emergency Department Sample (NEDS), Agency for Healthcare Research and Quality (AHRQ), based on data collected by individual States and provided to AHRQ by the States. Statistics based on estimates with a relative standard error (standard error / weighted estimate) greater than 0.30 or with standard error = 0 in the nationwide statistics (NIS, NEDS, and KID) are not reliable. These statistics are suppressed and are designated with an asterisk (*). The estimates of standard errors in HCUPnet were calculated using SUDAAN software. These estimates may differ slightly if other software packages are used to calculate variances."',Null,'False',Null,1,'Utilization'),
--('Recommended care','Not currently in use.',Null,Null,'False','Not currently in use.',2,'Patient safety'),
--('Results of care -- Deaths','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',2,'Patient safety'),
--('Results of care -- Complications','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',2,'Patient safety'),
--('Communication','"These ratings show how satisfied patients say they are with the way hospital staff communicated with them. Good communication means that hospital staff explained things clearly, listened carefully, and treated patients with courtesy and respect. These ratings are collected from patient surveys."',Null,Null,'False','"These ratings show how satisfied patients say they are with the way hospital staff communicated with them. Good communication means that hospital staff explained things clearly, listened carefully, and treated patients with courtesy and respect. These ratings are collected from patient surveys."',3,'Patient survey results'),
--('Environment','"These ratings show how satisfied patients say they are with the physical environment in the hospital. A good physical environment means that patients received help quickly, their pain was well-controlled, and the patient room was clean and quiet. This type of quality rating appears only in the "Patient survey results" health topic. These ratings are collected from patient surveys."',Null,Null,'False','"These ratings show how satisfied patients say they are with the physical environment in the hospital. A good physical environment means that patients received help quickly, their pain was well-controlled, and the patient room was clean and quiet. This type of quality rating appears only in the "Patient survey results" health topic. These ratings are collected from patient surveys."',3,'Patient survey results'),
--('Satisfaction overall','These ratings show how satisfied patients say they are with their recent hospital stay overall. This type of quality rating appears only in the "Patient survey results" health topic. These ratings are collected from patient surveys.',Null,Null,'False','These ratings show how satisfied patients say they are with their recent hospital stay overall. This type of quality rating appears only in the "Patient survey results" health topic. These ratings are collected from patient surveys.',3,'Patient survey results'),
--('Chronic Lung Conditions',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Summary scores',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Diabetes',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Heart Conditions',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Other Conditions',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Patient Safety',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Procedure Rates',Null,Null,Null,'False',Null,4,'Avoidable Stays Maps'),
--('Child health','Not currently in use.',Null,Null,'False','Not currently in use.',5,'Child health'),
--('Practice patterns','Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.',Null,Null,'False','Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.',6,'Childbirth'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',6,'Childbirth'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',7,'COPD(Chronic Obstructive Pulmonary Disease)'),
--('All Causes','"A higher number of deaths or returns to the hospital related to patient care, no matter why the patient was in the hospital, may mean the hospital is not treating people effectively."',Null,Null,'False','"A higher number of deaths or returns to the hospital related to patient care, no matter why the patient was in the hospital, may mean the hospital is not treating people effectively."',8,'Deaths or returns to the hospital'),
--('Summary scores',Null,Null,Null,'False',Null,8,'Deaths or returns to the hospital'),
--('Heart attack and chest pain','"A heart attack, also called an AMI or acute myocardial infarction, happens when the arteries leading to the heart become blocked and the blood supply slows or stops. A high number of deaths or returns to the hospital related to care for a heart attack may mean the hospital is not treating people effectively for these conditions."',Null,Null,'False','"A heart attack, also called an AMI or acute myocardial infarction, happens when the arteries leading to the heart become blocked and the blood supply slows or stops. A high number of deaths or returns to the hospital related to care for a heart attack may mean the hospital is not treating people effectively for these conditions."',8,'Deaths or returns to the hospital'),
--('Heart failure','Heart failure or congestive heart failure is a weakening of the heart''s pumping power that prevents the body from getting enough oxygen and nutrients to meet its needs. A high number of deaths or returns to the hospital related to care for a heart failure may mean the hospital is not treating people effectively for these conditions.',Null,Null,'False','Heart failure or congestive heart failure is a weakening of the heart''s pumping power that prevents the body from getting enough oxygen and nutrients to meet its needs. A high number of deaths or returns to the hospital related to care for a heart failure may mean the hospital is not treating people effectively for these conditions.',8,'Deaths or returns to the hospital'),
--('Heart surgeries and procedures','Heart surgeries and procedures related to the heart include  angioplasty and coronary bypass surgery. A high number of deaths or returns to the hospital related to heart surgeries or procedures may mean the hospital is not treating people effectively for these conditions or procedures.',Null,Null,'False','Heart surgeries and procedures related to the heart include  angioplasty and coronary bypass surgery. A high number of deaths or returns to the hospital related to heart surgeries or procedures may mean the hospital is not treating people effectively for these conditions or procedures.',8,'Deaths or returns to the hospital'),
--('Patient safety','Deaths or returns to the hospital related to both surgical and nonsurgical care. A high number of deaths or returns to the hospital related to how well the hospital keeps patients safe may mean the hospital is not taking steps to prevent safety problems from happening.',Null,Null,'False','Deaths or returns to the hospital related to both surgical and nonsurgical care. A high number of deaths or returns to the hospital related to how well the hospital keeps patients safe may mean the hospital is not taking steps to prevent safety problems from happening.',8,'Deaths or returns to the hospital'),
--('Other surgeries','Surgeries other than heart surgery such as brain surgery (craniotomy) and hip replacement surgery. A high number of deaths or returns to the hospital related to other surgeries may mean the hospital is not treating people effectively when they have these surgeries.',Null,Null,'False','Surgeries other than heart surgery such as brain surgery (craniotomy) and hip replacement surgery. A high number of deaths or returns to the hospital related to other surgeries may mean the hospital is not treating people effectively when they have these surgeries.',8,'Deaths or returns to the hospital'),
--('Pneumonia','"Pneumonia is a serious lung infection that causes difficulty breathing, fever, cough and fatigue. A high number of deaths or returns to the hospital related to care for pneumonia may mean the hospital is not treating people with pneumonia effectively."',Null,Null,'False','"Pneumonia is a serious lung infection that causes difficulty breathing, fever, cough and fatigue. A high number of deaths or returns to the hospital related to care for pneumonia may mean the hospital is not treating people with pneumonia effectively."',8,'Deaths or returns to the hospital'),
--('Stroke','A stroke happens when the blood supply to the brain stops.  A high number of deaths or returns to the hospital related to care for a stroke may mean the hospital is not treating people who have had a stroke effectively.',Null,Null,'False','A stroke happens when the blood supply to the brain stops.  A high number of deaths or returns to the hospital related to care for a stroke may mean the hospital is not treating people who have had a stroke effectively.',8,'Deaths or returns to the hospital'),
--('Surgical patient safety','Deaths or returns to the hospital related to surgical care. A high number of deaths or returns to the hospital related to surgical care may mean the hospital is not taking steps to prevent surgical safety problems from happening.',Null,Null,'False','Deaths or returns to the hospital related to surgical care. A high number of deaths or returns to the hospital related to surgical care may mean the hospital is not taking steps to prevent surgical safety problems from happening.',8,'Deaths or returns to the hospital'),
--('Throughput','Ratings about how quickly patients receive care in the Emergency Department (ED). Reducing the time patients remain in the emergency department can increase the availability of treatment and improve the care that patients receive.',Null,Null,'False','Ratings about how quickly patients receive care in the Emergency Department (ED). Reducing the time patients remain in the emergency department can increase the availability of treatment and improve the care that patients receive.',9,'Emergency department (ED)'),
--('Recommended care - Inpatient','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',10,'Heart attack and chest pain'),
--('Recommended care - Outpatient','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',10,'Heart attack and chest pain'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',10,'Heart attack and chest pain'),
--('Recommended care','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',11,'Heart failure'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',11,'Heart failure'),
--('Recommended care','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',12,'Heart surgeries and procedures'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',12,'Heart surgeries and procedures'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',13,'Hip or knee replacement surgery'),
--('Practice patterns','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice."',14,'Imaging'),
--('Healthcare-associated','"Health care-associated infections  are infections that people acquire while they are receiving treatment for another condition in a health care setting. HAIs can be acquired anywhere health care is delivered, including  hospitals, clinics, or nursing homes. HAIs may be caused by a bacteria or virus. A high number of health care associated infections may mean the hospital is not doing a good job at preventing infections."',Null,Null,'False','"Health care-associated infections  are infections that people acquire while they are receiving treatment for another condition in a health care setting. HAIs can be acquired anywhere health care is delivered, including  hospitals, clinics, or nursing homes. HAIs may be caused by a bacteria or virus. A high number of health care associated infections may mean the hospital is not doing a good job at preventing infections."',15,'Infections'),
--('Results of care - Complications','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',16,'Nursing care'),
--('Results of care - Deaths','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',16,'Nursing care'),
--('Practice patterns','Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.',Null,Null,'False','Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.',17,'Other surgeries'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',17,'Other surgeries'),
--('Recommended care','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',17,'Other surgeries'),
--('Recommended care','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures."',18,'Pneumonia'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',18,'Pneumonia'),
--('Blood Clot','Information about the number of patients who developed a blood clot while in the hospital and did not get treatment that could have prevented it.',Null,Null,'False','Information about the number of patients who developed a blood clot while in the hospital and did not get treatment that could have prevented it.',19,'Prevention and Treatment'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',20,'Stroke'),
--('Deaths','"Summary score that combines more than one rating related to the number of patients who die in the hospital into one score, including death as a result of medical conditions or major surgeries."',Null,Null,'False','"Summary score that combines more than one rating related to the number of patients who die in the hospital into one score, including death as a result of medical conditions or major surgeries."',21,'Summary Scores'),
--('Patient safety','Summary score that combine more than one rating related to how well the hospital keeps patients safe into one score.',Null,Null,'False','Summary score that combine more than one rating related to how well the hospital keeps patients safe into one score.',21,'Summary Scores'),
--('Recommended care before surgery','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice before a surgery."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice before a surgery."',22,'Surgical patient safety'),
--('Recommended care after surgery','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice after a surgery."',Null,Null,'False','"Information on how many patients got the care they needed such as the right medicine, surgery, or advice after a surgery."',22,'Surgical patient safety'),
--('Results of care','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',Null,Null,'False','Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.',22,'Surgical patient safety'),
--('Women health','Not currently in use.',Null,Null,'False','Not currently in use.',23,'Women health'),
--('Hip Replacement Cost and Quality',Null,Null,Null,'False',Null,25,'Health Care Cost and Quality'),
--('General Subtopic 1','General Subtopic 1','General Subtopic 1','HCUP County Hospital Stays Data','False',Null,26,'General Topic 1'),
--('General Subtopic 2','General Subtopic 2','General Subtopic 2','HCUP County Hospital Stays Data','False',Null,26,'General Topic 1'),
--('General Subtopic 3','General Subtopic 3','General Subtopic 3','HCUP County Hospital Stays Data','False',Null,27,'General Topic 2'),
--('General Subtopic 4','General Subtopic 4','General Subtopic 4','HCUP County Hospital Stays Data','False',Null,27,'General Topic 2'),
--('Results of care',Null,Null,Null,'False',Null,28,'COPD'),
--('Health Inspection',Null,Null,Null,'False',Null,24,'Nursing Home'),
--('Quality Measures',Null,Null,Null,'False',Null,24,'Nursing Home'),
--('Staffing',Null,Null,Null,'False',Null,24,'Nursing Home'))
--as source (Name,LongTitle,Description,WingTargetName,IsUserCreated,ConsumerLongTitle,TopicCategory_id,TopicCategoryName) on source.Name = target.Name
--WHEN MATCHED THEN 
--UPDATE SET target.Name = source.Name,
--		   target.LongTitle = source.LongTitle,
--		   target.Description = source.Description,
--		   target.WingTargetName = source.WingTargetName,
--		   target.IsUserCreated = source.IsUserCreated,
--		   target.ConsumerLongTitle = source.ConsumerLongTitle,
--		   target.TopicCategory_id = source.TopicCategory_id,
--		   target.TopicCategoryName = source.TopicCategoryName 
--WHEN NOT MATCHED THEN 
--		  INSERT (Name,LongTitle,Description,WingTargetName,IsUserCreated,ConsumerLongTitle,TopicCategory_id,TopicCategoryName) 
--		  VALUES(source.Name,source.LongTitle,source.Description,source.WingTargetName,source.IsUserCreated,source.ConsumerLongTitle,source.TopicCategory_id,source.TopicCategoryName);

INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Inpatient Hospital Utilization', N'Inpatient Hospital Care Utilizaton Statistics', N'Weighted national estimates from HCUP Nationwide Inpatient Sample (NIS), 2009, Agency for Healthcare Research and Quality (AHRQ), based on data collected by individual States and provided to AHRQ by the States. Total number of weighted discharges in the U.S. based on HCUP NIS = 39,434,956. Statistics based on estimates with a relative standard error (standard error / weighted estimate) greater than 0.30 or with standard error = 0 are not reliable, and are designated with a †.', NULL, 0, NULL, N'Utilization')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'ED Utilization', N'Emergency Department Treat and Release Utilizaton Statistics', N'Weighted national estimates from HCUP Nationwide Emergency Department Sample (NEDS), Agency for Healthcare Research and Quality (AHRQ), based on data collected by individual States and provided to AHRQ by the States. Statistics based on estimates with a relative standard error (standard error / weighted estimate) greater than 0.30 or with standard error = 0 in the nationwide statistics (NIS, NEDS, and KID) are not reliable. These statistics are suppressed and are designated with an asterisk (*). The estimates of standard errors in HCUPnet were calculated using SUDAAN software. These estimates may differ slightly if other software packages are used to calculate variances.', NULL, 0, NULL, N'Utilization')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care', N'Information on how many patients received the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients received the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Patient safety')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care -- Deaths', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Patient safety')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care -- Complications', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Patient safety')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Communication', N'These ratings show how satisfied patients say they are with the way hospital staff communicated with them. Good communication means that hospital staff explained things clearly, listened carefully, and treated patients with courtesy and respect. These ratings are collected from patient surveys.', N'', NULL, 0, N'Information about how well patients say hospital staff communicated with them, such as whether staff explained things clearly and listened to them carefully.', N'Patient survey results')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Environment', N'These ratings show how satisfied patients say they are with the physical environment in the hospital. A good physical environment means that patients received help quickly, their pain was well-controlled, and the patient room was clean and quiet. This type of quality rating appears only in the "Patient survey results" health topic. These ratings are collected from patient surveys.', N'', NULL, 0, N'Information about how patients describe the physical environment in the hospital such as whether they received help quickly, their pain was well-controlled, and their rooms were kept clean and quiet.', N'Patient survey results')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Satisfaction overall', N'These ratings show how satisfied patients say they are with their recent hospital stay overall. This type of quality rating appears only in the "Patient survey results" health topic. These ratings are collected from patient surveys.', N'', NULL, 0, N'Information about how patients rate their recent hospital stay overall and whether they would recommend the hospital to others.', N'Patient survey results')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Chronic Lung Conditions', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Summary scores', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Diabetes', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Heart Conditions', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Other Conditions', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Patient Safety', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Procedure Rates', N'', N'', NULL, 0, N'', N'Avoidable Stays Maps')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Child health', N'', N'', NULL, 0, N'', N'Child health')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Practice patterns', N'Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.', N'', NULL, 0, N'Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.', N'Childbirth')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Childbirth')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'COPD(Chronic Obstructive Pulmonary Disease)')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'All Causes', N'A higher number of deaths or returns to the hospital related to patient care, no matter why the patient was in the hospital, may mean the hospital is not treating people effectively.', N'', NULL, 0, N'A higher number of deaths or returns to the hospital related to patient care, no matter why the patient was in the hospital, may mean the hospital is not treating people effectively.', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Summary scores', N'', N'', NULL, 0, N'', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Heart attack and chest pain', N'A heart attack, also called an AMI or acute myocardial infarction, happens when the arteries leading to the heart become blocked and the blood supply slows or stops. A high number of deaths or returns to the hospital related to care for a heart attack may mean the hospital is not treating people effectively for these conditions.', N'', NULL, 0, N'A heart attack, also called an AMI or acute myocardial infarction, happens when the arteries leading to the heart become blocked and the blood supply slows or stops. A high number of deaths or returns to the hospital related to care for a heart attack may', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Heart failure', N'Heart failure or congestive heart failure is a weakening of the heart''s pumping power that prevents the body from getting enough oxygen and nutrients to meet its needs. A high number of deaths or returns to the hospital related to care for a heart failure may mean the hospital is not treating people effectively for these conditions.', N'', NULL, 0, N'Heart failure or congestive heart failure is a weakening of the heart''s pumping power that prevents the body from getting enough oxygen and nutrients to meet its needs. A high number of deaths or returns to the hospital related to care for a heart failure', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Heart surgeries and procedures', N'Heart surgeries and procedures related to the heart include  angioplasty and coronary bypass surgery. A high number of deaths or returns to the hospital related to heart surgeries or procedures may mean the hospital is not treating people effectively for these conditions or procedures.', N'', NULL, 0, N'Heart surgeries and procedures related to the heart include  angioplasty and coronary bypass surgery. A high number of deaths or returns to the hospital related to heart surgeries or procedures may mean the hospital is not treating people effectively for', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Patient safety', N'Deaths or returns to the hospital related to both surgical and nonsurgical care. A high number of deaths or returns to the hospital related to how well the hospital keeps patients safe may mean the hospital is not taking steps to prevent safety problems from happening.', N'', NULL, 0, N'Deaths or returns to the hospital related to both surgical and nonsurgical care. A high number of deaths or returns to the hospital related to how well the hospital keeps patients safe may mean the hospital is not taking steps to prevent safety problems f', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Other surgeries', N'Surgeries other than heart surgery such as brain surgery (craniotomy) and hip replacement surgery. A high number of deaths or returns to the hospital related to other surgeries may mean the hospital is not treating people effectively when they have these surgeries.', N'', NULL, 0, N'Surgeries other than heart surgery such as brain surgery (craniotomy) and hip replacement surgery. A high number of deaths or returns to the hospital related to other surgeries may mean the hospital is not treating people effectively when they have these', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Pneumonia', N'Pneumonia is a serious lung infection that causes difficulty breathing, fever, cough and fatigue. A high number of deaths or returns to the hospital related to care for pneumonia may mean the hospital is not treating people with pneumonia effectively.', N'', NULL, 0, N'Pneumonia is a serious lung infection that causes difficulty breathing, fever, cough and fatigue. A high number of deaths or returns to the hospital related to care for pneumonia may mean the hospital is not treating people with pneumonia effectively.', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Stroke', N'A stroke happens when the blood supply to the brain stops.  A high number of deaths or returns to the hospital related to care for a stroke may mean the hospital is not treating people who have had a stroke effectively.', N'', NULL, 0, N'A stroke happens when the blood supply to the brain stops.  A high number of deaths or returns to the hospital related to care for a stroke may mean the hospital is not treating people who have had a stroke effectively.', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Surgical patient safety', N'Deaths or returns to the hospital related to surgical care. A high number of deaths or returns to the hospital related to surgical care may mean the hospital is not taking steps to prevent surgical safety problems from happening.', N'', NULL, 0, N'Deaths or returns to the hospital related to surgical care. A high number of deaths or returns to the hospital related to surgical care may mean the hospital is not taking steps to prevent surgical safety problems from happening.', N'Deaths or returns to the hospital')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Throughput', N'Ratings about how quickly patients receive care in the Emergency Department (ED). Reducing the time patients remain in the emergency department can increase the availability of treatment and improve the care that patients receive.', N'', NULL, 0, N'Ratings about how quickly patients receive care in the Emergency Department (ED). Reducing the time patients remain in the emergency department can increase the availability of treatment and improve the care that patients receive.', N'Emergency department (ED)')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care - Inpatient', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Heart attack and chest pain')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care - Outpatient', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Heart attack and chest pain')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Heart attack and chest pain')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Heart failure')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Heart failure')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Heart surgeries and procedures')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Heart surgeries and procedures')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Hip or knee replacement surgery')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Practice patterns', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice.', N'Imaging')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Healthcare-associated', N'Health care-associated infections  are infections that people acquire while they are receiving treatment for another condition in a health care setting. HAIs can be acquired anywhere health care is delivered, including  hospitals, clinics, or nursing homes. HAIs may be caused by a bacteria or virus. A high number of health care associated infections may mean the hospital is not doing a good job at preventing infections.', N'', NULL, 0, N'Health care-associated infections  are infections that people acquire while they are receiving treatment for another condition in a health care setting. HAIs can be acquired anywhere health care is delivered, including  hospitals, clinics, or nursing home', N'Infections')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care - Complications', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Nursing care')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care - Deaths', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Nursing care')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Practice patterns', N'Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.', N'', NULL, 0, N'Information on the types of care provided in the hospital. This type of quality rating often shows information about the numbers of surgeries or procedures that a hospital performs.', N'Other surgeries')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Other surgeries')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Other surgeries')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice. These ratings are sometimes called process measures.', N'Pneumonia')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Pneumonia')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Blood Clot', N'Information about the number of patients who developed a blood clot while in the hospital and did not get treatment that could have prevented it.', N'', NULL, 0, N'Information about the number of patients who developed a blood clot while in the hospital and did not get treatment that could have prevented it.', N'Prevention and Treatment')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Stroke')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Deaths', N'Summary score that combines more than one rating related to the number of patients who die in the hospital into one score, including death as a result of medical conditions or major surgeries.', N'', NULL, 0, N'Summary score that combines more than one rating related to the number of patients who die in the hospital into one score, including death as a result of medical conditions or major surgeries.', N'Summary Scores')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Patient safety', N'Summary score that combine more than one rating related to how well the hospital keeps patients safe into one score.', N'', NULL, 0, N'Summary score that combine more than one rating related to how well the hospital keeps patients safe into one score.', N'Summary Scores')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care before surgery', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice before a surgery.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice before a surgery.', N'Surgical patient safety')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Recommended care after surgery', N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice after a surgery.', N'', NULL, 0, N'Information on how many patients got the care they needed such as the right medicine, surgery, or advice after a surgery.', N'Surgical patient safety')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Results of care', N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'', NULL, 0, N'Information on what happened to patients while being cared for in the hospital or after leaving the hospital. These ratings are sometimes called outcome measures.', N'Surgical patient safety')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Women health', N'', N'', NULL, 0, N'', N'Women health')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Hip replacement surgery', N'This table shows information about how well hospitals perform on hip replacement surgery for three topics:  (1) hospital quality, shown by how often patients die in the hospital after getting this surgery; (2) hospital cost, shown by the dollars the hospital usually spends on this surgery; and (3) how many surgeries are performed each year.', N'', NULL, 0, N'This table shows information about how well hospitals perform on hip replacement surgery for three topics:  (1) hospital quality, shown by how often patients die in the hospital after getting this surgery; (2) hospital cost, shown by the dollars the hospi', N'Health Care Cost and Quality')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'General Subtopic 1', N'General Subtopic 1', N'General Subtopic 1', N'HCUP County Hospital Stays Data', 0, NULL, N'General Topic 1')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'General Subtopic 2', N'General Subtopic 2', N'General Subtopic 2', N'HCUP County Hospital Stays Data', 0, NULL, N'General Topic 1')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'General Subtopic 3', N'General Subtopic 3', N'General Subtopic 3', N'HCUP County Hospital Stays Data', 0, NULL, N'General Topic 2')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'General Subtopic 4', N'General Subtopic 4', N'General Subtopic 4', N'HCUP County Hospital Stays Data', 0, NULL, N'General Topic 2')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Health Inspection', NULL, NULL, NULL, 0, NULL, N'Nursing Home')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Quality Measures', NULL, NULL, NULL, 0, NULL, N'Nursing Home')
INSERT TopicTemp ([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName]) VALUES (N'Staffing', NULL, NULL, NULL, 0, NULL, N'Nursing Home')


INSERT INTO TopicTemp([Name], [LongTitle], [Description], [WingTargetName], [IsUserCreated], [ConsumerLongTitle], [TopicCategoryName])
SELECT temp.Name, temp.LongTitle, temp.Description, temp.WingTargetName, 1, temp.ConsumerLongTitle, tc.Name as TopicCategoryName
FROM Topics temp
	INNER JOIN TopicCategories tc on temp.TopicCategory_id = tc.Id
WHERE not exists (SELECT [Name], [TopicCategoryName] FROM TopicTemp t WHERE temp.Name = t.Name and tc.Name = t.TopicCategoryName) 


END TRY
BEGIN CATCH
DECLARE @ErrorMessage VARCHAR(5000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;

    SELECT @ErrorMessage = 'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(50)) +' Error: ' + ERROR_MESSAGE(),
           @ErrorSeverity = ERROR_SEVERITY(),
           @ErrorState = ERROR_STATE();

    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState); 

END CATCH