//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monahrq.Sdk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monahrq.Sdk.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONAHRQ Error: No view was flagged as the shell view..
        /// </summary>
        public static string ApplicationService_Starting_MONAHRQ_Error_No_view
        {
            get {
                return ResourceManager.GetString("ApplicationService_Starting_MONAHRQ_Error_No_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Shell resolved to {1}.
        /// </summary>
        public static string ApplicationService_Starting_ShellResolved
        {
            get {
                return ResourceManager.GetString("ApplicationService_Starting_ShellResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property does not have a get method..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_NoGetter
        {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_NoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_NotAMember
        {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_NotAMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_NotAProperty
        {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_NotAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_Static
        {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished loading module {0}.
        /// </summary>
        public static string DeploymentService_DeploymentCatalogDownloadCompleted_Finished
        {
            get {
                return ResourceManager.GetString("DeploymentService_DeploymentCatalogDownloadCompleted_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load required module. Please contact the system administrator..
        /// </summary>
        public static string DeploymentService_DeploymentCatalogDownloadCompleted_ModuleNotFound
        {
            get {
                return ResourceManager.GetString("DeploymentService_DeploymentCatalogDownloadCompleted_ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModelRoute: {0} binds to {1}.
        /// </summary>
        public static string ViewModelRoute_ToString_ViewModelRoute
        {
            get {
                return ResourceManager.GetString("ViewModelRoute_ToString_ViewModelRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : activate view {1}.
        /// </summary>
        public static string ViewModelRouter_ActivateView
        {
            get {
                return ResourceManager.GetString("ViewModelRouter_ActivateView", resourceCulture);
            }
        }
    }
}
