-- =============================================
-- Author:		Shafiul Alam
-- Project:		MONAHRQ 6.0 Build 1
-- Create date: 12-22-2014
-- Description:	This is the update script from older MONAHRQ 5.0 Measures table to the new 
--              MONAHRQ 6.0 database schema.
--				'Measures Data'
-- =============================================

BEGIN TRY


UPDATE Measures
SET    ClassType              = 'HOSPITAL',
       UsedInCalculations     = 0;
       
ALTER TABLE Measures ALTER COLUMN [MeasureType] NVARCHAR(100)

IF NOT EXISTS (SELECT 1 FROM sys.indexes i WHERE object_name(i.[object_id])='Measures' AND i.name='IDX_Measures')
CREATE NONCLUSTERED INDEX [IDX_Measures]
    ON [dbo].[Measures]([MeasureType] ASC, [IsOverride] ASC, [IsLibEdit] ASC, [UsedInCalculations] ASC);
       
/*****************************************************
 *  Dropping foreign Keys in Measures table
 *****************************************************/

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[Target_owns_Measure_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[Measures]'))
ALTER TABLE [dbo].Measures DROP CONSTRAINT Target_owns_Measure_FK

/************************************************************
 * Insert Nursing Home Measures
 ************************************************************/

IF NOT EXISTS (SELECT 1 FROM Measures m WHERE ClassType='NURSINGHOME')
BEGIN
	
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-OA-01', N'Nursing Home', N'ProviderInfo', N'This is the weighted total of selected scores on health inspections, quality measures, and staffing measures', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Overall Rating', N'Overall Rating', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-HI-01', N'Health Inspection', N'ProviderInfo', N'This data is based on the results of the three most recent annual and complaint-related health inspection surveys. Scores are calculated based on the number, scope, and severity of minimum standards that are not met and the number of revisits needed to confirm compliance. Stars are assigned based on performance within a State - for instance, only the top ten percent of performers in a State receive a five star rating.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Overall Health Inspection', N'Overall Health Inspection', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-01', N'Staffing', N'ProviderInfo', N'This is an overall score based on 7 of the 13 individual scores.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Overall Quality Measures', N'Overall Quality', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-HI-02', N'Health Inspection', N'SurveySummary', N'This is the date of the most recent standard health inspection conducted at this nursing home. These inspections take place about once a year but may be done more often if a nursing home is performing poorly.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Health Survey Date', N'Date of most recent health inspection.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-HI-03', N'Health Inspection', N'SurveySummary', N'This is the date of the most recent fire safety inspection conducted at this nursing home.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Fire Safety Survey Data', N'Date of most recent fire safety inspection.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-HI-04', N'Health Inspection', N'SurveySummary', N'This number takes into account minimum standards designed to protect residents, such as those related to care of residents, interactions between residents and staff, management of medication, storage and preparation of food, and the nursing home environment.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Total Number of Health Deficiencies', N'How many health-related standards nursing home failed to meet.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-HI-05', N'Health Inspection', N'SurveySummary', N'This number takes into account a wide range of fire protection standards set by the National Fire Protection Agency.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Total Number of Fire Safety Deficiencies', N'How many fire safety standards nursing home failed to meet.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-SS-01', N'Quality Measures Short Stay', N'QualityMsr', N'The percent of short-stay residents (at the nursing home for 100 days or less) who self-reported at least one episode of moderate/severe pain or horrible/excruciating pain of any frequency in a specific 5 day period.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents who Self-Report Moderate to Severe Pain (Short Stay)', N'How many residents, out of 100, with a short nursing home stay, reported moderate to severe pain?', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-SS-02', N'Quality Measures Short Stay', N'QualityMsr', N'The percent of short-stay residents (staying at the nursing home for 100 days or less) with new or worsened pressure sores during their stay.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents with Pressure Ulcers that are New or Worsened (Short Stay)', N'How many residents, out of 100, with a short nursing home stay, had new pressure sores or sores that got worse.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-SS-03', N'Quality Measures Short Stay', N'QualityMsr', N'The percent of short-stay residents (staying at the nursing home for 100 days or less) who were assessed and appropriately given the flu vaccine during the current or most recent flu season as of reporting.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Who Were Assessed and Appropriately Given the Seasonal Influenza Vaccine (Short Stay)', N'How many residents, out of 100, with a short nursing home stay, got a flu vaccine if needed.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-SS-04', N'Quality Measures Short Stay', N'QualityMsr', N'The percent of short-stay residents (staying at the nursing home for 100 days or less) who were assessed and appropriately vaccinated against the bacteria that causes pneumonia.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Assessed and Appropriately Given the Pneumococcal Vaccine (Short Stay)', N'How many residents, out of 100, with a short nursing home stay, got a pneumonia vaccine if needed.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-SS-05', N'Quality Measures Short Stay', N'QualityMsr', N'The percent of short-stay residents (staying at the nursing home for 100 days or less) who received antipsychotic medication  their stay but were not receiving it at their initial assessment.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Short-Stay Residents Who Newly Received an Antipsychotic Medication', N'How many residents, out of 100, with a short nursing home stay, got medicine for a serious mental illness for the first time.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-01', N'Quality Measures Long Stay', N'QualityMsr', N'The number of long-term residents who had one or more falls with a major injury (such as a bone fracture, dislocated joint, or closed head injury) in a 12-month period.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Experiencing One or More Falls with Major Injury (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, had a fall leading to a major injury?', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-02', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of short-stay residents who self-reported at least one episode of moderate/severe pain or horrible/excruciating pain of any frequency in a specific 5 day period.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents who Self-Report Moderate to Severe Pain (Long Stay)', N'How many residents, out of 100, with a long nursing home stay reported moderate to severe pain.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-03', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay, high-risk residents (considered high risk due to malnutrition, loss of mobility, or being comatose) who got new or worsened pressure sores during their stay.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of High-Risk Residents with Pressure Ulcers (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, had a new pressure sores or sores that got worse.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-04', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents who were assessed and appropriately given the flu vaccine during the current or most recent flu season as of reporting.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Assessed and Appropriately Given the Seasonal Influenza Vaccine (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, got a flu vaccine if needed.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-05', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents who were assessed and appropriately vaccinated against the bacteria that causes pneumonia.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Assessed and Appropriately Given the Pneumococcal Vaccine (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, got a pneumonia vaccine if needed.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-06', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents who had a urinary tract infection in a 30-day period. .', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents with a Urinary Tract Infection (Long Stay)', N'How many residents, out of 100, with a long nursing homes stay, get an infection in their bladder.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-07', N'Quality Measures Long Stay', N'QualityMsr', N'Percent of long-stay low-risk residents who often or always lose control of their bowels or bladder.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Low-Risk Residents Who Lose Control of Their Bowels or Bladder (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, lose control of bladder or bowels.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-08', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents who had an indwelling catheter in a specific 7-day period.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Who Have/Had a Catheter Inserted and Left in Their Bladder (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, had catheter inserted and left in their bladder.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-09', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents who were physically restrained on a daily basis.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Who Were Physically Restrained (Long Stay)', N'How many residents, out 100, with a long nursing home stay, were physically restrained.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-10', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents whose need for help with late-loss Activities of Daily Living (such as bed mobility, transfer, eating, and toileting) has increased when compared to the prior assessment.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 1, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Whose Need for Help with Activities of Daily Living Has Increased (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, need more help doing daily tasks.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-11', N'Quality Measures Long Stay', N'QualityMsr', N'The percentage of long-stay residents not on a prescribed weight-loss regimen who lost 5% or more in a specific one month period or 10% or more in a specific 3 month period.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Who Lose Too Much Weight (Long Stay)', N'How many residents, out of 100, with a long nursing home stay, lost too much weight.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-12', N'Quality Measures Long Stay', N'QualityMsr', N'This measure reports the percentage of long-stay residents who had symptoms of depression duringa specific 2-week period.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Residents Who Have Depressive Symptoms (Long Stay)', N'How many residents, out 100, with a long nursing home stay, began to be depressed.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-QM-LS-13', N'Quality Measures Long Stay', N'QualityMsr', N'The percent of long-stay residents who received antipsychotic medication.', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Percent of Long-Stay Residents Who Received An Antipsychotic Medication', N'How many residents, out 100, with a long nursing home stay, got medicine for a serious mental illness.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-01', N'Staffing', N'ProviderInfo', N'This is an overall score based on all 6 individual scores', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Overall Staffing', N'Overall Staffing', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-02', N'Staffing', N'ProviderInfo', N'This was calculated in two steps: (1) the number of hours worked by CNAs each day during a specific 2 week period was computed, and (2) the number of hours worked was divided by the number of residents', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Reported CNA Staffing Hours per Resident per Day', N'Hours of help from nursing aides that each resident can get day.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-03', N'Staffing', N'ProviderInfo', N'This was calculated in two steps: (1) the number of hours worked by LPN/LVNs each day during a specific 2 week period was computed, and (2) the number of hours worked was divided by the number of residents', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Reported LPN Staffing Hours per Resident per Day', N'Hours of help from licensed vocational or practical nurses (LVN, LPN) that each resident can get each day.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-04', N'Staffing', N'ProviderInfo', N'This was calculated in two steps: (1) the number of hours worked by RNs each day during a specific 2 week period was computed, and (2) thenumber of hours worked was divided by the number of residents', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Reported RN Staffing Hours per Resident per Day', N'Hours of help from Registered Nurses that each resident can get each day.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-05', N'Staffing', N'ProviderInfo', N'This is the number of hours worked by licensed staff (RN and LPN/LVN) each day at the nursing home per resident. This is computed by adding the "Number of RN Hours Available per resident per day" and "Number of LPN/LVN Hours Available Per Resident per Day."', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Reported Licensed Staffing Hours per Resident per Day', N'Hours of help from any licensed nurse (LVN, LPN, RN) that each resident can get each day.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-06', N'Staffing', N'ProviderInfo', N'This is the total number of hours worked by all nursing staff (RN, LPN/LVN, and CNA) each day at the nursing home per resident. This is computed by adding the "Number of licensed staff (RN, LPN/ LVN) Hours Available per Resident per Day" and "Numer of CNA Hours Available per Resident per Day"', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Reported Total Nurse Staffing Hours per Resident per Day', N'Hours of help from any kind of nurse that each resident can get each day.', NULL, N'Plain', NULL, N'Calculated_Mean')
INSERT [dbo].[Measures] ([ClassType], [Name], [MeasureType], [Source], [Description], [MoreInformation], [Footnotes], [NationalBenchmark], [HigherScoresAreBetter], [ScaleBy], [ScaleTarget], [RiskAdjustedMethod], [RateLabel], [NQFEndorsed], [NQFID], [SuppressionDenominator], [SuppressionNumerator], [PerformMarginSuppression], [UpperBound], [LowerBound], [Url], [UrlTitle], [IsOverride], [IsLibEdit], [UsedInCalculations], [Target_id], [ClinicalTitle], [PlainTitle], [PolicyTitle], [SelectedTitle], [ProvidedBenchmark], [CalculationMethod]) 
VALUES (N'NURSINGHOME', N'NH-SD-07', N'Staffing', N'ProviderInfo', N'This was calculated in two steps: (1) the number of hours worked by PTs each day during a specific 2 week period was computed, and (2) the number of hours worked was divided by the number of residents', NULL, N'0', NULL, 1, CAST(1 AS Decimal(19, 0)), N'TBD', N'NO', N'0', 0, N'', CAST(0 AS Decimal(19, 0)), CAST(0 AS Decimal(19, 0)), 0, NULL, NULL, NULL, NULL, 0, 0, 0, (Select top 1 Id from Wings_Targets where Name = 'Nursing Home Compare Data'), N'Reported Physical Therapist Staffing Hours per Resident Per Day', N'Hours of help from a physical therapis available to each resident each day.', NULL, N'Plain', NULL, N'Calculated_Mean')

END;

/*****************************************************
 *  Creating Region Id foreign Keys in Measures table
 *****************************************************/

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[Target_owns_Measure_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[Measures]'))
BEGIN
ALTER TABLE [dbo].[Measures]  WITH CHECK ADD  CONSTRAINT [Target_owns_Measure_FK] FOREIGN KEY(Target_id)
REFERENCES [dbo].Wings_Targets ([Id])
ALTER TABLE [dbo].[Measures] CHECK CONSTRAINT [Target_owns_Measure_FK]

END;


       
SELECT 1;

END TRY
BEGIN CATCH
    DECLARE @ErrorMessage VARCHAR(5000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;

    SELECT @ErrorMessage = 'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(50)) +' Error: ' + ERROR_MESSAGE(),
           @ErrorSeverity = ERROR_SEVERITY(),
           @ErrorState = ERROR_STATE();

    RAISERROR (@ErrorMessage, -- Message text.
               @ErrorSeverity, -- Severity.
               @ErrorState -- State.
               );
END CATCH;